import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@merchant/ui/globals.css";
import ApiProvider from "@/components/api-provider";
import TopLoader from "@merchant/ui/components/top-loader";
import { ThemeProvider } from "@merchant/ui/providers/theme-provider";

const font = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${font.variable} antialiased`}>
        <TopLoader />
        <ApiProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
